/* ------------------------------------------------------------------
   pit.js — procedural pit lane for the F1 race-replay game.

   Self-contained ES module. THREE is passed in as an argument so the
   host page's importmap stays the single source of truth for three.

   The pit lane is generated by laterally offsetting the track's own
   centreline (geom.posAt / geom.tanAt) over an arc-length window that
   normally straddles the start/finish line, with a smooth taper at
   both ends so the lane merges into the racing line instead of
   teleporting away from it.

   Exports:
     buildPitLane(THREE, geom, opts)
     animatePitCrew(group, dt, activeBox)
     pitStopPhases(elapsed, opts)
   ------------------------------------------------------------------ */

/* =============================== helpers =============================== */

/** Hermite smoothstep. */
function smoothstep(x) {
  x = x < 0 ? 0 : x > 1 ? 1 : x;
  return x * x * (3 - 2 * x);
}

/** Tiny deterministic PRNG so crew placement is stable between runs. */
function rng(seed) {
  let n = seed | 0;
  return function () {
    n = (n + 1831565813) | 0;
    let t = Math.imul(n ^ (n >>> 15), 1 | n);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* Seven-segment digit patterns: [a,b,c,d,e,f,g] (top, tr, br, bottom, bl, tl, mid) */
const SEG7 = {
  '0': [1, 1, 1, 1, 1, 1, 0],
  '1': [0, 1, 1, 0, 0, 0, 0],
  '2': [1, 1, 0, 1, 1, 0, 1],
  '3': [1, 1, 1, 1, 0, 0, 1],
  '4': [0, 1, 1, 0, 0, 1, 1],
  '5': [1, 0, 1, 1, 0, 1, 1],
  '6': [1, 0, 1, 1, 1, 1, 1],
  '7': [1, 1, 1, 0, 0, 0, 0],
  '8': [1, 1, 1, 1, 1, 1, 1],
  '9': [1, 1, 1, 1, 0, 1, 1]
};

/**
 * Build a flat 7-segment number out of scaled unit boxes (no textures).
 * Lives in the local XY plane, centred on the origin, `depth` thick in Z.
 */
function makeNumber(THREE, str, height, depth, material, unitBox) {
  const g = new THREE.Group();
  const h = height;
  const w = h * 0.62;         // digit width
  const t = h * 0.15;         // stroke thickness
  const gap = h * 0.22;       // gap between digits
  const total = str.length * w + (str.length - 1) * gap;

  // segment definitions: [cx, cy, sx, sy]
  const segDef = [
    [0, h / 2, w - t, t],          // a top
    [w / 2 - t / 2, h / 4, t, h / 2 - t],   // b top-right
    [w / 2 - t / 2, -h / 4, t, h / 2 - t],  // c bottom-right
    [0, -h / 2, w - t, t],         // d bottom
    [-w / 2 + t / 2, -h / 4, t, h / 2 - t], // e bottom-left
    [-w / 2 + t / 2, h / 4, t, h / 2 - t],  // f top-left
    [0, 0, w - t, t]               // g middle
  ];

  for (let i = 0; i < str.length; i++) {
    const pat = SEG7[str[i]];
    if (!pat) continue;
    const x0 = -total / 2 + w / 2 + i * (w + gap);
    for (let s = 0; s < 7; s++) {
      if (!pat[s]) continue;
      const d = segDef[s];
      const m = new THREE.Mesh(unitBox, material);
      m.position.set(x0 + d[0], d[1], 0);
      m.scale.set(d[2], d[3], depth);
      g.add(m);
    }
  }
  return g;
}

/* ================================ main ================================= */

/**
 * Build the pit lane.
 *
 * @param {object} THREE  the three.js namespace (from the host importmap)
 * @param {object} geom   track geometry: { LAP, ds, posAt(s,v), tanAt(s,v), speedAt(s) }
 * @param {object} opts   see defaults below
 * @returns {{group, entryS, exitS, boxS, boxUs, length, pathAt, tangentAt,
 *            lateralAt, boxIndexFor, boxUFor, boxCount, laneWidth, triangles}}
 */
export function buildPitLane(THREE, geom, opts) {
  opts = opts || {};

  const LAP = geom.LAP;
  const UP = new THREE.Vector3(0, 1, 0);

  /* --------------------------- configuration --------------------------- */
  const entryS = (opts.entryS !== undefined ? opts.entryS : 0.93 * LAP);
  const exitS = (opts.exitS !== undefined ? opts.exitS : 0.07 * LAP);
  const side = opts.side !== undefined ? opts.side : -1;   // -1 = inside of the circuit
  const offset = opts.offset !== undefined ? opts.offset : 16;   // metres from centreline
  const laneWidth = opts.laneWidth !== undefined ? opts.laneWidth : 12;
  const nBoxes = opts.boxes !== undefined ? opts.boxes : 10;
  const yLift = opts.yLift !== undefined ? opts.yLift : 0.08;
  const speedLimit = opts.speedLimit !== undefined ? opts.speedLimit : 80;
  const seed = opts.seed !== undefined ? opts.seed : 7;

  // Arc length of the lane, measured forwards from entry (wraps through 0).
  let length = exitS - entryS;
  length = ((length % LAP) + LAP) % LAP;
  if (length < 1) length = LAP;             // degenerate window -> whole lap

  // Taper distance at each end. Capped as a fraction of the lane so short
  // pit lanes (small circuits) still leave room for the boxes in the middle.
  const taper = Math.min(
    opts.taper !== undefined ? opts.taper : 60,
    length * 0.28
  );

  const halfW = laneWidth / 2;
  const rand = rng(seed);

  /* ------------------------- lane centre geometry ---------------------- */

  // scratch vectors (module-level reuse would break re-entrancy across lanes)
  const _t = new THREE.Vector3();
  const _l = new THREE.Vector3();
  const _a = new THREE.Vector3();
  const _b = new THREE.Vector3();

  /** Lateral (right-hand) unit vector at arc length s — matches game.js. */
  function lateralAt(s, out) {
    geom.tanAt(s, _t);
    return (out || new THREE.Vector3()).crossVectors(_t, UP).normalize();
  }

  /** Offset profile: 0 at both ends, 1 across the middle. */
  function profile(u) {
    const d = u * length;                       // metres from entry
    const dIn = taper > 0 ? smoothstep(d / taper) : 1;
    const dOut = taper > 0 ? smoothstep((length - d) / taper) : 1;
    return dIn * dOut;
  }

  /** Signed lateral displacement of the lane centre at u. */
  function laneOffset(u) {
    return side * offset * profile(u);
  }

  /**
   * World position of the pit-lane centreline at u in [0,1].
   * u = 0 is exactly the racing line at entryS, u = 1 exactly at exitS.
   */
  function pathAt(u, outVec3) {
    const out = outVec3 || new THREE.Vector3();
    u = u < 0 ? 0 : u > 1 ? 1 : u;
    const s = entryS + u * length;
    geom.posAt(s, out);
    const o = laneOffset(u);
    if (o !== 0) {
      lateralAt(s, _l);
      out.addScaledVector(_l, o);
    }
    out.y += yLift;
    return out;
  }

  /** Unit tangent of the pit lane at u (numeric derivative of pathAt). */
  function tangentAt(u, outVec3) {
    const out = outVec3 || new THREE.Vector3();
    const h = 0.5 / length;                    // ~0.5 m in u-space
    const u0 = Math.max(0, u - h);
    const u1 = Math.min(1, u + h);
    pathAt(u0, _a);
    pathAt(u1, _b);
    out.subVectors(_b, _a);
    if (out.lengthSq() < 1e-12) geom.tanAt(entryS + u * length, out);
    return out.normalize();
  }

  /** Lane-local right vector (perpendicular to the *lane*, not the track). */
  function laneRight(u, out) {
    tangentAt(u, _t);
    return (out || new THREE.Vector3()).crossVectors(_t, UP).normalize();
  }

  /* --------------------------- mesh utilities -------------------------- */

  const group = new THREE.Group();
  group.name = 'pitLane';

  const M = {
    asphalt: new THREE.MeshLambertMaterial({ color: 0x3a3d46 }),
    white: new THREE.MeshLambertMaterial({ color: 0xf2f4f8 }),
    yellow: new THREE.MeshLambertMaterial({ color: 0xf4c430 }),
    wall: new THREE.MeshLambertMaterial({ color: 0xdfe3ea, side: THREE.DoubleSide }),
    wallTop: new THREE.MeshLambertMaterial({ color: 0xd6455a, side: THREE.DoubleSide }),
    garage: new THREE.MeshLambertMaterial({ color: 0x6b7590 }),
    garageDark: new THREE.MeshLambertMaterial({ color: 0x39415c }),
    roof: new THREE.MeshLambertMaterial({ color: 0x2f3a5c }),
    signRed: new THREE.MeshLambertMaterial({ color: 0xd6273c }),
    dark: new THREE.MeshLambertMaterial({ color: 0x1b1f2a }),
    rubber: new THREE.MeshLambertMaterial({ color: 0x22242c }),
    gun: new THREE.MeshLambertMaterial({ color: 0xff8c1a })
  };
  // one colour per garage, saturated + cartoon-y
  const TEAM = [
    0xe8402a, 0x1f7ae0, 0xf5c518, 0x2fb36b, 0xa855f7,
    0xff7ab2, 0x00c2d1, 0xff9d2e, 0x8ecb2b, 0xc0392b
  ];
  const teamMats = TEAM.map(c => new THREE.MeshLambertMaterial({ color: c }));

  // Shared low-poly primitives, reused (cloned meshes, never cloned geometry).
  const G = {
    unitBox: new THREE.BoxGeometry(1, 1, 1),
    torso: new THREE.CylinderGeometry(0.26, 0.32, 0.78, 6, 1),
    head: new THREE.SphereGeometry(0.19, 6, 4),
    limb: new THREE.BoxGeometry(0.14, 0.6, 0.14),
    leg: new THREE.BoxGeometry(0.16, 0.62, 0.18),
    tyre: new THREE.CylinderGeometry(0.36, 0.36, 0.26, 8, 1),
    gunBody: new THREE.CylinderGeometry(0.09, 0.09, 0.5, 6, 1),
    post: new THREE.BoxGeometry(0.22, 1, 0.22)
  };

  /**
   * Horizontal ribbon following the lane between two lateral offsets.
   * `n` samples, offsets may vary with u via functions.
   */
  function ribbon(uA, uB, wLeft, wRight, y, material, n) {
    const pos = [];
    const nor = [];
    const idx = [];
    const pa = new THREE.Vector3();
    const pb = new THREE.Vector3();
    let v = 0;
    for (let i = 0; i <= n; i++) {
      const u = uA + (uB - uA) * (i / n);
      const wl = typeof wLeft === 'function' ? wLeft(u) : wLeft;
      const wr = typeof wRight === 'function' ? wRight(u) : wRight;
      lanepointInto(u, wl, y, pa);
      lanepointInto(u, wr, y, pb);
      pos.push(pa.x, pa.y, pa.z, pb.x, pb.y, pb.z);
      nor.push(0, 1, 0, 0, 1, 0);
      if (i > 0) idx.push(v - 2, v - 1, v, v, v - 1, v + 1);
      v += 2;
    }
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
    g.setAttribute('normal', new THREE.Float32BufferAttribute(nor, 3));
    g.setIndex(idx);
    const mesh = new THREE.Mesh(g, material);
    mesh.receiveShadow = true;
    return mesh;
  }

  // laneRight needs its own scratch inside ribbon loops
  const _lr = new THREE.Vector3();
  function lanepointInto(u, w, y, out) {
    pathAt(u, out);
    if (w) {
      laneRight(u, _lr);
      out.addScaledVector(_lr, w);
    }
    if (y) out.y += y;
    return out;
  }

  /** Vertical ribbon (a wall) following the lane at lateral offset `w`. */
  function wallStrip(uA, uB, w, y0, y1, material, n) {
    const pos = [];
    const nor = [];
    const idx = [];
    const p = new THREE.Vector3();
    let v = 0;
    for (let i = 0; i <= n; i++) {
      const u = uA + (uB - uA) * (i / n);
      laneRight(u, _lr);
      lanepointInto(u, w, 0, p);
      pos.push(p.x, p.y + y0, p.z, p.x, p.y + y1, p.z);
      nor.push(-_lr.x, 0, -_lr.z, -_lr.x, 0, -_lr.z);
      if (i > 0) idx.push(v - 2, v - 1, v, v, v - 1, v + 1);
      v += 2;
    }
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
    g.setAttribute('normal', new THREE.Float32BufferAttribute(nor, 3));
    g.setIndex(idx);
    return new THREE.Mesh(g, material);
  }

  /* ------------------------------ surfaces ----------------------------- */

  const nSeg = Math.max(24, Math.min(420, Math.round(length / 3)));

  // Lane tarmac. The lane narrows into the racing line at the tapered ends
  // so the merge reads as a real blend rather than a step.
  const widen = u => 0.35 + 0.65 * profile(u);
  group.add(ribbon(0, 1, u => -halfW * widen(u), u => halfW * widen(u), 0, M.asphalt, nSeg));

  // Painted edge lines on both sides of the lane.
  group.add(ribbon(0, 1, u => -halfW * widen(u) - 0.16, u => -halfW * widen(u) + 0.16, 0.02, M.white, nSeg));
  group.add(ribbon(0, 1, u => halfW * widen(u) - 0.16, u => halfW * widen(u) + 0.16, 0.02, M.white, nSeg));

  // The pit-limit line: separates the fast lane (track side) from the working
  // lane (garage side). Only drawn where the lane is actually a lane.
  const uWork0 = Math.min(0.45, (taper * 0.85) / length);
  const uWork1 = 1 - uWork0;
  group.add(ribbon(uWork0, uWork1, -0.14, 0.14, 0.03, M.white,
    Math.max(12, Math.round(nSeg * (uWork1 - uWork0)))));

  // Transverse white lines marking the speed-limit zone at entry and exit.
  for (const u of [uWork0 * 0.55, 1 - uWork0 * 0.55]) {
    const du = 0.35 / length;
    group.add(ribbon(u - du, u + du, -halfW, halfW, 0.04, M.white, 2));
  }

  /* ------------------------------ pit wall ----------------------------- */
  // The lane centre is displaced by `side * offset`, so in lane-local
  // coordinates the circuit always lies on the -side edge of the lane.
  const wallOffset = (side > 0 ? -1 : 1) * (halfW + 0.6);
  const nWall = Math.max(16, Math.round(nSeg * (uWork1 - uWork0)));
  group.add(wallStrip(uWork0, uWork1, wallOffset, 0, 1.05, M.wall, nWall));
  group.add(wallStrip(uWork0, uWork1, wallOffset, 1.05, 1.25, M.wallTop, nWall));
  // thin cap so the wall reads as solid from above
  group.add(ribbon(uWork0, uWork1, wallOffset - 0.18, wallOffset + 0.18, 1.25, M.wall, nWall));

  /* --------------------------- garage boxes ---------------------------- */
  // Boxes live in the flat middle of the lane, on the far side from the track.
  //
  // Everything below is authored inside a per-box "anchor" whose rotation.y is
  // atan2(tan.x, tan.z) — the same convention the game uses for cars, so the
  // anchor's local +z is the direction of travel. Note that with that rotation
  // the anchor's local +x works out to be *minus* `laneRight`, so the sign that
  // points away from the circuit in anchor space is the opposite of `side`.
  const garSign = side > 0 ? -1 : 1;   // anchor-local x, away from the circuit
  const uA = uWork0 + 0.035;
  const uB = uWork1 - 0.035;
  const span = uB - uA;
  const boxUs = [];
  for (let i = 0; i < nBoxes; i++) {
    boxUs.push(uA + span * ((i + 0.5) / nBoxes));
  }
  const spacingM = (span * length) / nBoxes;          // metres between box centres
  const stallW = Math.min(7.5, spacingM * 0.86);      // box width along the lane
  const stallD = Math.min(9, Math.max(5, stallW * 1.1)); // garage depth

  const crews = [];
  const tmpPos = new THREE.Vector3();
  const tmpTan = new THREE.Vector3();

  for (let i = 0; i < nBoxes; i++) {
    const u = boxUs[i];
    const mat = teamMats[i % teamMats.length];

    // A local frame for the whole box so everything can be authored in
    // straightforward local coordinates (x = across the lane, z = along it).
    const anchor = new THREE.Group();
    pathAt(u, tmpPos);
    tangentAt(u, tmpTan);
    anchor.position.copy(tmpPos);
    anchor.rotation.y = Math.atan2(tmpTan.x, tmpTan.z);
    // lane-local +x points to `laneRight`; the anchor's local +x is
    // laneRight as well because rotation.y aligns local +z with the tangent.
    group.add(anchor);

    const gx = garSign * (halfW + stallD / 2 + 0.2);  // garage centre, across lane
    const px = garSign * (halfW * 0.42);              // working area / stopped car

    // --- painted stall on the tarmac
    const stall = new THREE.Mesh(G.unitBox, mat);
    stall.scale.set(halfW * 0.78, 0.04, stallW * 0.62);
    stall.position.set(garSign * (halfW * 0.55), 0.03, 0);
    anchor.add(stall);

    // --- garage building. The front face sits at |x| = halfW + 0.2; every
    //     decoration below is pushed *outside* that plane so it stays visible.
    const bldH = 4.2;
    const faceX = garSign * (halfW + 0.2);
    const bld = new THREE.Mesh(G.unitBox, M.garage);
    bld.scale.set(stallD, bldH, stallW * 0.9);   // gap between neighbours
    bld.position.set(gx, bldH / 2, 0);
    bld.castShadow = true;
    anchor.add(bld);

    // dark separator pillars so ten garages don't read as one long block
    for (const sgn of [-1, 1]) {
      const pil = new THREE.Mesh(G.unitBox, M.garageDark);
      pil.scale.set(0.5, bldH + 0.5, stallW * 0.1);
      pil.position.set(faceX + garSign * 0.2, (bldH + 0.5) / 2, sgn * stallW * 0.47);
      anchor.add(pil);
    }

    // team-coloured roller door, protruding slightly from the face
    const door = new THREE.Mesh(G.unitBox, mat);
    door.scale.set(0.45, bldH * 0.6, stallW * 0.66);
    door.position.set(faceX - garSign * 0.1, bldH * 0.3, 0);
    anchor.add(door);

    // team band across the top of the front face
    const band = new THREE.Mesh(G.unitBox, mat);
    band.scale.set(0.35, 0.28, stallW * 0.86);
    band.position.set(faceX - garSign * 0.08, bldH * 0.95, 0);
    anchor.add(band);

    // roof overhang / awning
    const roof = new THREE.Mesh(G.unitBox, M.roof);
    roof.scale.set(stallD + 2.2, 0.34, stallW * 0.94);
    roof.position.set(gx - garSign * 1.0, bldH + 0.17, 0);
    anchor.add(roof);

    // --- box number on the garage face (7-segment boxes, no textures)
    const num = makeNumber(THREE, String(i + 1), 1.05, 0.14, M.white, G.unitBox);
    num.position.set(faceX - garSign * 0.28, bldH * 0.74, 0);
    // the plane of the digits must face the lane, i.e. -garSign along local x
    num.rotation.y = garSign > 0 ? -Math.PI / 2 : Math.PI / 2;
    anchor.add(num);

    // --- tyre stack beside the door
    const stack = new THREE.Group();
    for (let k = 0; k < 3; k++) {
      const t = new THREE.Mesh(G.tyre, M.rubber);
      t.position.y = 0.14 + k * 0.27;
      t.castShadow = true;
      stack.add(t);
    }
    // just in front of the garage face, clear of the building
    stack.position.set(garSign * (halfW - 0.5), 0, stallW * 0.44);
    anchor.add(stack);

    /* --- pit crew ---------------------------------------------------- */
    // 5 figures: 2 wheel guns (front/rear), 1 jack man, 2 helpers.
    const crew = { members: [], jack: null, guns: [], act: 0, t: rand() * 6.28 };
    const layout = [
      { x: px + garSign * 0.9, z: -1.5, role: 'gun' },   // front-left gun
      { x: px + garSign * 0.9, z: 1.5, role: 'gun' },    // rear-left gun
      { x: px + garSign * 2.1, z: -0.2, role: 'help' },
      { x: px + garSign * 2.1, z: 1.9, role: 'help' },
      { x: 0, z: -2.9, role: 'jackman' }                 // front jack man
    ];
    for (let c = 0; c < layout.length; c++) {
      const L = layout[c];
      const fig = new THREE.Group();
      fig.position.set(L.x, 0, L.z);
      fig.rotation.y = (L.role === 'jackman' ? Math.PI : (garSign > 0 ? -Math.PI / 2 : Math.PI / 2))
        + (rand() - 0.5) * 0.3;

      const torso = new THREE.Mesh(G.torso, mat);
      torso.position.y = 1.02;
      torso.castShadow = true;
      fig.add(torso);

      const head = new THREE.Mesh(G.head, M.white);
      head.position.y = 1.56;
      fig.add(head);

      const armL = new THREE.Mesh(G.limb, mat);
      armL.position.set(-0.32, 1.08, 0.12);
      armL.rotation.x = -0.5;
      fig.add(armL);
      const armR = new THREE.Mesh(G.limb, mat);
      armR.position.set(0.32, 1.08, 0.12);
      armR.rotation.x = -0.5;
      fig.add(armR);

      for (const sgn of [-1, 1]) {
        const lg = new THREE.Mesh(G.leg, M.dark);
        lg.position.set(sgn * 0.14, 0.32, 0);
        fig.add(lg);
      }

      const member = {
        node: fig, arms: [armL, armR], torso, role: L.role,
        baseY: 0, phase: rand() * 6.28, baseRotY: fig.rotation.y
      };

      if (L.role === 'gun') {
        const gun = new THREE.Mesh(G.gunBody, M.gun);
        gun.position.set(0, 1.0, 0.42);
        gun.rotation.x = Math.PI / 2;
        fig.add(gun);
        member.gun = gun;
        crew.guns.push(gun);
      }
      anchor.add(fig);
      crew.members.push(member);
    }

    // Air jack: a simple wedge in front of the stopped car that rises.
    const jack = new THREE.Mesh(G.unitBox, M.yellow);
    jack.scale.set(1.5, 0.22, 0.55);
    jack.position.set(px, 0.14, -2.2);
    anchor.add(jack);
    crew.jack = jack;
    crew.jackBaseY = jack.position.y;
    crews.push(crew);
  }

  /* ------------------------ speed-limit sign at entry ------------------- */
  {
    const uSign = Math.min(0.5, uWork0 * 0.5);
    const sg = new THREE.Group();
    pathAt(uSign, tmpPos);
    tangentAt(uSign, tmpTan);
    sg.position.copy(tmpPos);
    sg.rotation.y = Math.atan2(tmpTan.x, tmpTan.z);

    const lat = garSign * (halfW + 1.2);

    const post = new THREE.Mesh(G.post, M.dark);
    post.scale.y = 2.6;
    post.position.set(lat, 1.3, 0);
    sg.add(post);

    const panel = new THREE.Mesh(G.unitBox, M.white);
    panel.scale.set(0.16, 1.7, 1.7);
    panel.position.set(lat, 3.1, 0);
    sg.add(panel);

    // red rim sits just behind the white face so it reads as a ring
    const rim = new THREE.Mesh(G.unitBox, M.signRed);
    rim.scale.set(0.1, 2.05, 2.05);
    rim.position.set(lat + garSign * 0.06, 3.1, 0);
    sg.add(rim);

    // digits in front of the panel, facing the lane (-garSign along local x)
    const digits = makeNumber(THREE, String(speedLimit), 0.95, 0.12, M.dark, G.unitBox);
    digits.position.set(lat - garSign * 0.16, 3.1, 0);
    digits.rotation.y = garSign > 0 ? -Math.PI / 2 : Math.PI / 2;
    sg.add(digits);

    group.add(sg);
    group.userData.signPos = sg.position.clone();
  }

  /* ------------------------------- result ------------------------------ */

  // Count triangles so callers (and tests) can keep an eye on the budget.
  let triangles = 0;
  group.traverse(o => {
    if (!o.isMesh || !o.geometry) return;
    const g2 = o.geometry;
    triangles += g2.index ? g2.index.count / 3 : g2.attributes.position.count / 3;
  });

  group.userData.pit = {
    crews,
    boxUs,
    time: 0,
    nBoxes,
    triangles
  };

  function boxS(i) {
    i = ((i | 0) % nBoxes + nBoxes) % nBoxes;
    return boxUs[i];
  }

  // Lateral shift (in `laneRight` metres) from the lane centre to a stall,
  // so a stopped car sits in its box rather than in the middle of the lane.
  const boxLateral = Math.sign(side) * halfW * 0.42;

  /** Exact world position a car should occupy when stopped in box i. */
  function boxPosAt(i, outVec3) {
    const out = outVec3 || new THREE.Vector3();
    const u = boxS(i);
    pathAt(u, out);
    const r = laneRight(u, new THREE.Vector3());
    return out.addScaledVector(r, boxLateral);
  }

  return {
    group,
    entryS,
    exitS,
    length,
    laneWidth,
    boxCount: nBoxes,
    boxUs,
    triangles,
    /** u-value along the lane of pit box i (0..nBoxes-1). */
    boxS,
    /** signed lateral offset (metres, along lateralAt) from lane centre to a stall */
    boxLateral,
    /** world position of the stall for box i */
    boxPosAt,
    /** which pit box a given car index owns. */
    boxIndexFor(carIdx) {
      return ((carIdx | 0) % nBoxes + nBoxes) % nBoxes;
    },
    /** convenience: u-value of the box owned by a given car index. */
    boxUFor(carIdx) {
      return boxS(((carIdx | 0) % nBoxes + nBoxes) % nBoxes);
    },
    pathAt,
    tangentAt,
    lateralAt
  };
}

/* ============================== animation ============================== */

/**
 * Idle + working animation for the crews.
 *
 * @param {THREE.Group} group      the group returned by buildPitLane
 * @param {number} dt              seconds since last call
 * @param {number} activeBox       index of the box with a car in it, or -1
 */
export function animatePitCrew(group, dt, activeBox) {
  const pit = group && group.userData && group.userData.pit;
  if (!pit) return;
  if (activeBox === undefined || activeBox === null) activeBox = -1;

  pit.time += dt;
  const T = pit.time;

  for (let i = 0; i < pit.crews.length; i++) {
    const crew = pit.crews[i];
    const want = i === activeBox ? 1 : 0;
    // ease the "working" weight so crews don't snap between states
    crew.act += (want - crew.act) * Math.min(1, dt * 6);
    const a = crew.act;

    for (let m = 0; m < crew.members.length; m++) {
      const mem = crew.members[m];
      const ph = mem.phase;

      // idle: slow weight shift + a little look-around
      const idleY = Math.sin(T * 1.6 + ph) * 0.02;
      // working: quick crouch/pump
      const workY = Math.sin(T * 11 + ph) * 0.13 - 0.1;
      mem.node.position.y = mem.baseY + idleY * (1 - a) + workY * a;

      mem.node.rotation.y = mem.baseRotY + Math.sin(T * 0.7 + ph) * 0.12 * (1 - a);

      // arms: relaxed when idle, thrust forward/down when working
      const armIdle = -0.45 + Math.sin(T * 1.3 + ph) * 0.08;
      const armWork = -1.25 + Math.sin(T * 13 + ph) * 0.35;
      const arm = armIdle * (1 - a) + armWork * a;
      mem.arms[0].rotation.x = arm;
      mem.arms[1].rotation.x = arm;

      // lean into the car while working
      mem.torso.rotation.x = 0.35 * a;

      // wheel guns spin while working
      if (mem.gun) {
        mem.gun.rotation.y += dt * 26 * a;
        mem.gun.position.z = 0.42 + 0.18 * a;
      }
    }

    // air jack rises when the car is in the box
    if (crew.jack) {
      crew.jack.position.y = crew.jackBaseY + 0.34 * a;
      crew.jack.rotation.x = -0.12 * a;
    }
  }
}

/* ============================ stop timeline ============================ */

/**
 * Timeline for a pit stop.
 *
 *   approach : rolling down the pit lane to the box
 *   box      : final crawl / lining up in the stall
 *   stopped  : stationary, tyres being changed
 *   release  : jack drops, car starts moving
 *   exit     : accelerating back out to the lane exit
 *
 * @param {number} elapsed seconds since the car crossed the pit entry
 * @param {object} opts    per-phase durations (seconds)
 * @returns {{phase, progress, done, elapsed, total, index, overall, tyreChange}}
 */
export function pitStopPhases(elapsed, opts) {
  opts = opts || {};
  const d = {
    approach: opts.approach !== undefined ? opts.approach : 3.2,
    box: opts.box !== undefined ? opts.box : 0.9,
    stopped: opts.stopped !== undefined ? opts.stopped : 2.6,
    release: opts.release !== undefined ? opts.release : 0.7,
    exit: opts.exit !== undefined ? opts.exit : 3.4
  };
  const order = ['approach', 'box', 'stopped', 'release', 'exit'];
  const total = d.approach + d.box + d.stopped + d.release + d.exit;

  let t = elapsed;
  if (!(t >= 0)) t = 0;

  if (t >= total) {
    return {
      phase: 'done', progress: 1, done: true,
      elapsed: t, total, index: order.length, overall: 1, tyreChange: 1
    };
  }

  let acc = 0;
  for (let i = 0; i < order.length; i++) {
    const name = order[i];
    const dur = d[name];
    if (t < acc + dur || i === order.length - 1) {
      const progress = dur > 0 ? Math.min(1, (t - acc) / dur) : 1;
      // how far through the tyre change we are (0 before the stop, 1 after)
      const tcStart = d.approach + d.box;
      const tyreChange = Math.max(0, Math.min(1, (t - tcStart) / Math.max(1e-6, d.stopped)));
      return {
        phase: name,
        progress,
        done: false,
        elapsed: t,
        total,
        index: i,
        overall: t / total,
        tyreChange
      };
    }
    acc += dur;
  }
  // unreachable
  return { phase: 'done', progress: 1, done: true, elapsed: t, total, index: order.length, overall: 1, tyreChange: 1 };
}
